require:
 - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Metrics/BlockLength:
  Max: 36
  Exclude:
    - spec/**/*.rb

Metrics/ClassLength:
  Max: 150

Style/Documentation:
  Enabled: false
