require:
 - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Metrics/BlockLength:
  Max: 36
  Exclude:
    - spec/**/*.rb

Metrics/ClassLength:
  Max: 150

Style/Documentation:
  Enabled: false
